const builtinCourses = [
  {
    course_name: '日常口语基础',
    description: '日常生活中最常用的基础短句，适合英语初学者',
    difficulty: 'easy',
    category: '日常',
    sentences: [
      { english: 'Hello, how are you?', chinese: '你好，你怎么样？', phonetic: '/həˈloʊ, haʊ ɑːr juː/' },
      { english: 'Good morning!', chinese: '早上好！', phonetic: '/ɡʊd ˈmɔːrnɪŋ/' },
      { english: 'Good afternoon!', chinese: '下午好！', phonetic: '/ɡʊd ˌæftərˈnuːn/' },
      { english: 'Good evening!', chinese: '晚上好！', phonetic: '/ɡʊd ˈiːvnɪŋ/' },
      { english: 'Good night!', chinese: '晚安！', phonetic: '/ɡʊd naɪt/' },
      { english: 'Thank you very much.', chinese: '非常感谢你。', phonetic: '/θæŋk juː ˈveri mʌtʃ/' },
      { english: 'You are welcome.', chinese: '不客气。', phonetic: '/juː ɑːr ˈwelkəm/' },
      { english: 'Excuse me.', chinese: '打扰一下。', phonetic: '/ɪkˈskjuːz miː/' },
      { english: 'I am sorry.', chinese: '对不起。', phonetic: '/aɪ æm ˈsɑːri/' },
      { english: 'It is okay.', chinese: '没关系。', phonetic: '/ɪt ɪz oʊˈkeɪ/' },
      { english: 'Nice to meet you.', chinese: '很高兴认识你。', phonetic: '/naɪs tuː miːt juː/' },
      { english: 'What is your name?', chinese: '你叫什么名字？', phonetic: '/wʌt ɪz jʊr neɪm/' },
      { english: 'My name is Tom.', chinese: '我叫汤姆。', phonetic: '/maɪ neɪm ɪz tɑːm/' },
      { english: 'How old are you?', chinese: '你多大了？', phonetic: '/haʊ oʊld ɑːr juː/' },
      { english: 'I am twenty years old.', chinese: '我二十岁。', phonetic: '/aɪ æm ˈtwenti jɪrz oʊld/' },
      { english: 'See you tomorrow.', chinese: '明天见。', phonetic: '/siː juː təˈmɑːroʊ/' },
      { english: 'See you later.', chinese: '回头见。', phonetic: '/siː juː ˈleɪtər/' },
      { english: 'Have a nice day!', chinese: '祝你今天愉快！', phonetic: '/hæv ə naɪs deɪ/' },
      { english: 'I am fine, thank you.', chinese: '我很好，谢谢你。', phonetic: '/aɪ æm faɪn, θæŋk juː/' },
      { english: 'Take care!', chinese: '保重！', phonetic: '/teɪk ker/' },
    ],
  },
  {
    course_name: '校园英语入门',
    description: '学生在校园场景中使用的基础英语表达',
    difficulty: 'easy',
    category: '校园',
    sentences: [
      { english: 'What class do you have next?', chinese: '你下一节是什么课？', phonetic: '/wʌt klæs duː juː hæv nekst/' },
      { english: 'I have math class.', chinese: '我有数学课。', phonetic: '/aɪ hæv mæθ klæs/' },
      { english: 'Where is the library?', chinese: '图书馆在哪里？', phonetic: '/wer ɪz ðə ˈlaɪbreri/' },
      { english: 'The library is on the second floor.', chinese: '图书馆在二楼。', phonetic: '/ðə ˈlaɪbreri ɪz ɑːn ðə ˈsekənd flɔːr/' },
      { english: 'May I borrow a pen?', chinese: '我可以借一支笔吗？', phonetic: '/meɪ aɪ ˈbɑːroʊ ə pen/' },
      { english: 'Can you help me with this problem?', chinese: '你能帮我解决这个问题吗？', phonetic: '/kæn juː help miː wɪð ðɪs ˈprɑːbləm/' },
      { english: 'Let us go to the classroom.', chinese: '我们去教室吧。', phonetic: '/let ʌs goʊ tuː ðə ˈklæsruːm/' },
      { english: 'The teacher is coming.', chinese: '老师来了。', phonetic: '/ðə ˈtiːtʃər ɪz ˈkʌmɪŋ/' },
      { english: 'Please open your books.', chinese: '请打开你们的书。', phonetic: '/pliːz ˈoʊpən jʊr bʊks/' },
      { english: 'I forgot my homework.', chinese: '我忘记带作业了。', phonetic: '/aɪ fərˈɡɑːt maɪ ˈhoʊmwɜːrk/' },
      { english: 'When is the homework due?', chinese: '作业什么时候交？', phonetic: '/wen ɪz ðə ˈhoʊmwɜːrk duː/' },
      { english: 'The exam is next Monday.', chinese: '考试在下周一。', phonetic: '/ði ɪɡˈzæm ɪz nekst ˈmʌndeɪ/' },
      { english: 'I need to study harder.', chinese: '我需要更努力学习。', phonetic: '/aɪ niːd tuː ˈstʌdi ˈhɑːrdər/' },
      { english: 'What is your favorite subject?', chinese: '你最喜欢的科目是什么？', phonetic: '/wʌt ɪz jʊr ˈfeɪvərɪt ˈsʌbdʒɪkt/' },
      { english: 'My favorite subject is English.', chinese: '我最喜欢的科目是英语。', phonetic: '/maɪ ˈfeɪvərɪt ˈsʌbdʒɪkt ɪz ˈɪŋɡlɪʃ/' },
      { english: 'Let us study together.', chinese: '我们一起学习吧。', phonetic: '/let ʌs ˈstʌdi təˈɡeðər/' },
      { english: 'The bell is ringing.', chinese: '铃响了。', phonetic: '/ðə bel ɪz ˈrɪŋɪŋ/' },
      { english: 'Class is over.', chinese: '下课了。', phonetic: '/klæs ɪz ˈoʊvər/' },
      { english: 'Do you want to have lunch together?', chinese: '你想一起吃午饭吗？', phonetic: '/duː juː wɑːnt tuː hæv lʌntʃ təˈɡeðər/' },
      { english: 'See you after school.', chinese: '放学后见。', phonetic: '/siː juː ˈæftər skuːl/' },
    ],
  },
  {
    course_name: '生活场景常用',
    description: '日常生活场景中频繁使用的实用英语',
    difficulty: 'easy',
    category: '生活',
    sentences: [
      { english: 'What time is it?', chinese: '现在几点了？', phonetic: '/wʌt taɪm ɪz ɪt/' },
      { english: 'It is half past three.', chinese: '现在三点半。', phonetic: '/ɪt ɪz hæf pæst θriː/' },
      { english: 'I am hungry.', chinese: '我饿了。', phonetic: '/aɪ æm ˈhʌŋɡri/' },
      { english: 'I am thirsty.', chinese: '我渴了。', phonetic: '/aɪ æm ˈθɜːrsti/' },
      { english: 'I am tired.', chinese: '我累了。', phonetic: '/aɪ æm ˈtaɪərd/' },
      { english: 'Let us take a break.', chinese: '我们休息一下吧。', phonetic: '/let ʌs teɪk ə breɪk/' },
      { english: 'What do you want to eat?', chinese: '你想吃什么？', phonetic: '/wʌt duː juː wɑːnt tuː iːt/' },
      { english: 'I want some water.', chinese: '我想要一些水。', phonetic: '/aɪ wɑːnt sʌm ˈwɔːtər/' },
      { english: 'Could you repeat that?', chinese: '你能再说一遍吗？', phonetic: '/kʊd juː rɪˈpiːt ðæt/' },
      { english: 'I do not understand.', chinese: '我不明白。', phonetic: '/aɪ duː nɑːt ˌʌndərˈstænd/' },
      { english: 'Can you speak slower?', chinese: '你能说慢一点吗？', phonetic: '/kæn juː spiːk ˈsloʊər/' },
      { english: 'What does this word mean?', chinese: '这个单词是什么意思？', phonetic: '/wʌt dʌz ðɪs wɜːrd miːn/' },
      { english: 'How do you spell that?', chinese: '那个怎么拼写？', phonetic: '/haʊ duː juː spel ðæt/' },
      { english: 'I think you are right.', chinese: '我觉得你是对的。', phonetic: '/aɪ θɪŋk juː ɑːr raɪt/' },
      { english: 'I am not sure about that.', chinese: '我不太确定。', phonetic: '/aɪ æm nɑːt ʃʊr əˈbaʊt ðæt/' },
      { english: 'Let me think for a moment.', chinese: '让我想一下。', phonetic: '/let miː θɪŋk fɔːr ə ˈmoʊmənt/' },
      { english: 'That is a good idea.', chinese: '好主意。', phonetic: '/ðæt ɪz ə ɡʊd aɪˈdiːə/' },
      { english: 'I agree with you.', chinese: '我同意你的看法。', phonetic: '/aɪ əˈɡriː wɪð juː/' },
      { english: 'No problem at all.', chinese: '完全没问题。', phonetic: '/noʊ ˈprɑːbləm æt ɔːl/' },
      { english: 'Wait a minute, please.', chinese: '请等一下。', phonetic: '/weɪt ə ˈmɪnɪt, pliːz/' },
    ],
  },
  {
    course_name: '美食英语基础',
    description: '点餐、用餐相关的基础英语表达',
    difficulty: 'easy',
    category: '美食',
    sentences: [
      { english: 'I would like to order, please.', chinese: '我想点餐，谢谢。', phonetic: '/aɪ wʊd laɪk tuː ˈɔːrdər, pliːz/' },
      { english: 'Can I have the menu?', chinese: '请给我菜单好吗？', phonetic: '/kæn aɪ hæv ðə ˈmenjuː/' },
      { english: 'What do you recommend?', chinese: '你有什么推荐的吗？', phonetic: '/wʌt duː juː ˌrekəˈmend/' },
      { english: 'I will have this one.', chinese: '我要这个。', phonetic: '/aɪ wɪl hæv ðɪs wʌn/' },
      { english: 'A bowl of rice, please.', chinese: '请来一碗米饭。', phonetic: '/ə boʊl ʌv raɪs, pliːz/' },
      { english: 'I want a cup of coffee.', chinese: '我想要一杯咖啡。', phonetic: '/aɪ wɑːnt ə kʌp ʌv ˈkɔːfi/' },
      { english: 'Do you have any vegetarian dishes?', chinese: '你们有素菜吗？', phonetic: '/duː juː hæv ˈeni ˌvedʒəˈteriən ˈdɪʃɪz/' },
      { english: 'This is delicious!', chinese: '这个真好吃！', phonetic: '/ðɪs ɪz dɪˈlɪʃəs/' },
      { english: 'Can I have some more water?', chinese: '可以再给我一些水吗？', phonetic: '/kæn aɪ hæv sʌm mɔːr ˈwɔːtər/' },
      { english: 'The food is too spicy for me.', chinese: '这个菜对我来说太辣了。', phonetic: '/ðə fuːd ɪz tuː ˈspaɪsi fɔːr miː/' },
      { english: 'Check, please.', chinese: '请结账。', phonetic: '/tʃek, pliːz/' },
      { english: 'Can I pay by WeChat?', chinese: '可以用微信支付吗？', phonetic: '/kæn aɪ peɪ baɪ wiːtʃæt/' },
      { english: 'Let us split the bill.', chinese: '我们AA制吧。', phonetic: '/let ʌs splɪt ðə bɪl/' },
      { english: 'It is my treat today.', chinese: '今天我请客。', phonetic: '/ɪt ɪz maɪ triːt təˈdeɪ/' },
      { english: 'I am full, thank you.', chinese: '我吃饱了，谢谢你。', phonetic: '/aɪ æm fʊl, θæŋk juː/' },
      { english: 'Do you have a table for two?', chinese: '你们有两个人的位子吗？', phonetic: '/duː juː hæv ə ˈteɪbl fɔːr tuː/' },
      { english: 'I have a reservation under Tom.', chinese: '我用汤姆的名字预订了。', phonetic: '/aɪ hæv ə ˌrezərˈveɪʃn ˈʌndər tɑːm/' },
      { english: 'Is this dish sweet?', chinese: '这个菜是甜的吗？', phonetic: '/ɪz ðɪs dɪʃ swiːt/' },
      { english: 'Could you bring me chopsticks?', chinese: '请给我拿双筷子好吗？', phonetic: '/kʊd juː brɪŋ miː ˈtʃɑːpstɪks/' },
      { english: 'Thank you for the meal.', chinese: '谢谢你的款待。', phonetic: '/θæŋk juː fɔːr ðə miːl/' },
    ],
  },
  {
    course_name: '购物英语会话',
    description: '购物场景中需要的实用英语表达（中等难度）',
    difficulty: 'medium',
    category: '购物',
    sentences: [
      { english: 'I am just looking around, thank you.', chinese: '我只是随便看看，谢谢。', phonetic: '/aɪ æm dʒʌst ˈlʊkɪŋ əˈraʊnd, θæŋk juː/' },
      { english: 'Can I try this on?', chinese: '我可以试穿这件吗？', phonetic: '/kæn aɪ traɪ ðɪs ɑːn/' },
      { english: 'Where is the fitting room?', chinese: '试衣间在哪里？', phonetic: '/wer ɪz ðə ˈfɪtɪŋ ruːm/' },
      { english: 'What size do you wear?', chinese: '你穿多大号的？', phonetic: '/wʌt saɪz duː juː wer/' },
      { english: 'Do you have this in a smaller size?', chinese: '这个有小一号的吗？', phonetic: '/duː juː hæv ðɪs ɪn ə ˈsmɔːlər saɪz/' },
      { english: 'This is too tight for me.', chinese: '这个对我来说太紧了。', phonetic: '/ðɪs ɪz tuː taɪt fɔːr miː/' },
      { english: 'How much does this cost?', chinese: '这个多少钱？', phonetic: '/haʊ mʌtʃ dʌz ðɪs kɔːst/' },
      { english: 'Is there any discount?', chinese: '有折扣吗？', phonetic: '/ɪz ðer ˈeni ˈdɪskaʊnt/' },
      { english: 'That is a little too expensive.', chinese: '那个有点太贵了。', phonetic: '/ðæt ɪz ə ˈlɪtl tuː ɪkˈspensɪv/' },
      { english: 'Can you give me a better price?', chinese: '能给我便宜点吗？', phonetic: '/kæn juː ɡɪv miː ə ˈbetər praɪs/' },
      { english: 'I will take it.', chinese: '我买了。', phonetic: '/aɪ wɪl teɪk ɪt/' },
      { english: 'Do you accept credit cards?', chinese: '你们接受信用卡吗？', phonetic: '/duː juː əkˈsept ˈkredɪt kɑːrdz/' },
      { english: 'I would like to return this item.', chinese: '我想退掉这件商品。', phonetic: '/aɪ wʊd laɪk tuː rɪˈtɜːrn ðɪs ˈaɪtəm/' },
      { english: 'Do you have a receipt?', chinese: '你有收据吗？', phonetic: '/duː juː hæv ə rɪˈsiːt/' },
      { english: 'I would like a refund, please.', chinese: '我想退款，谢谢。', phonetic: '/aɪ wʊd laɪk ə ˈriːfʌnd, pliːz/' },
      { english: 'What colors do you have?', chinese: '你们有什么颜色？', phonetic: '/wʌt ˈkʌlərz duː juː hæv/' },
      { english: 'Does this come with a warranty?', chinese: '这个有保修吗？', phonetic: '/dʌz ðɪs kʌm wɪð ə ˈwɔːrənti/' },
      { english: 'Can you gift-wrap this for me?', chinese: '能帮我包装成礼品吗？', phonetic: '/kæn juː ɡɪft ræp ðɪs fɔːr miː/' },
      { english: 'Could you deliver it to my home?', chinese: '可以送货上门吗？', phonetic: '/kʊd juː dɪˈlɪvər ɪt tuː maɪ hoʊm/' },
      { english: 'I would like to exchange this for a larger size.', chinese: '我想换一件大一号的。', phonetic: '/aɪ wʊd laɪk tuː ɪksˈtʃeɪndʒ ðɪs fɔːr ə ˈlɑːrdʒər saɪz/' },
    ],
  },
  {
    course_name: '交通出行英语',
    description: '出行、问路、乘坐交通工具的英语表达（中等难度）',
    difficulty: 'medium',
    category: '交通',
    sentences: [
      { english: 'Excuse me, how do I get to the subway station?', chinese: '打扰一下，请问怎么去地铁站？', phonetic: '/ɪkˈskjuːz miː, haʊ duː aɪ ɡet tuː ðə ˈsʌbweɪ ˈsteɪʃn/' },
      { english: 'Go straight and turn left at the first intersection.', chinese: '直走，在第一个路口左转。', phonetic: '/ɡoʊ streɪt ænd tɜːrn left æt ðə fɜːrst ˌɪntərˈsekʃn/' },
      { english: 'How long does it take to get there?', chinese: '到那里需要多长时间？', phonetic: '/haʊ lɔːŋ dʌz ɪt teɪk tuː ɡet ðer/' },
      { english: 'It takes about twenty minutes by bus.', chinese: '坐公交车大约需要二十分钟。', phonetic: '/ɪt teɪks əˈbaʊt ˈtwenti ˈmɪnɪts baɪ bʌs/' },
      { english: 'Where can I take a taxi?', chinese: '我在哪里可以打车？', phonetic: '/wer kæn aɪ teɪk ə ˈtæksi/' },
      { english: 'Please take me to this address.', chinese: '请带我去这个地址。', phonetic: '/pliːz teɪk miː tuː ðɪs əˈdres/' },
      { english: 'Could you please slow down a bit?', chinese: '可以开慢一点吗？', phonetic: '/kʊd juː pliːz sloʊ daʊn ə bɪt/' },
      { english: 'Please stop here.', chinese: '请在这里停。', phonetic: '/pliːz stɑːp hɪr/' },
      { english: 'How much is the fare?', chinese: '车费多少钱？', phonetic: '/haʊ mʌtʃ ɪz ðə fer/' },
      { english: 'Keep the change.', chinese: '不用找零了。', phonetic: '/kiːp ðə tʃeɪndʒ/' },
      { english: 'Which bus goes to the airport?', chinese: '哪路公交车去机场？', phonetic: '/wɪtʃ bʌs ɡoʊz tuː ði ˈerpɔːrt/' },
      { english: 'Where is the nearest bus stop?', chinese: '最近的公交站在哪里？', phonetic: '/wer ɪz ðə ˈnɪrɪst bʌs stɑːp/' },
      { english: 'I need to transfer at the next stop.', chinese: '我需要在下一站换乘。', phonetic: '/aɪ niːd tuː trænsˈfɜːr æt ðə nekst stɑːp/' },
      { english: 'What time does the last train leave?', chinese: '末班车几点发车？', phonetic: '/wʌt taɪm dʌz ðə læst treɪn liːv/' },
      { english: 'I think I am lost.', chinese: '我想我迷路了。', phonetic: '/aɪ θɪŋk aɪ æm lɔːst/' },
      { english: 'Can you show me on the map?', chinese: '你能在地图上指给我看吗？', phonetic: '/kæn juː ʃoʊ miː ɑːn ðə mæp/' },
      { english: 'Is it within walking distance?', chinese: '走路能到吗？', phonetic: '/ɪz ɪt wɪˈðɪn ˈwɔːkɪŋ ˈdɪstəns/' },
      { english: 'I would like to buy a round-trip ticket.', chinese: '我想买一张往返票。', phonetic: '/aɪ wʊd laɪk tuː baɪ ə raʊnd trɪp ˈtɪkɪt/' },
      { english: 'My flight is boarding now.', chinese: '我的航班开始登机了。', phonetic: '/maɪ flaɪt ɪz ˈbɔːrdɪŋ naʊ/' },
      { english: 'Please fasten your seatbelt.', chinese: '请系好安全带。', phonetic: '/pliːz ˈfæsn jʊr ˈsiːtbelt/' },
    ],
  },
  {
    course_name: '办公英语基础',
    description: '办公室日常沟通使用的英语表达（中等难度）',
    difficulty: 'medium',
    category: '办公',
    sentences: [
      { english: 'Good morning, everyone.', chinese: '大家早上好。', phonetic: '/ɡʊd ˈmɔːrnɪŋ, ˈevriwʌn/' },
      { english: 'Let us start the meeting.', chinese: '我们开始开会吧。', phonetic: '/let ʌs stɑːrt ðə ˈmiːtɪŋ/' },
      { english: 'Could you please send me the report?', chinese: '能把报告发给我吗？', phonetic: '/kʊd juː pliːz send miː ðə rɪˈpɔːrt/' },
      { english: 'I will finish it by the end of today.', chinese: '我会在今天下班前完成。', phonetic: '/aɪ wɪl ˈfɪnɪʃ ɪt baɪ ði end ʌv təˈdeɪ/' },
      { english: 'Let me check my schedule.', chinese: '让我看一下我的日程。', phonetic: '/let miː tʃek maɪ ˈskedʒuːl/' },
      { english: 'I am available on Tuesday afternoon.', chinese: '我周二下午有空。', phonetic: '/aɪ æm əˈveɪləbl ɑːn ˈtuːzdeɪ ˌæftərˈnuːn/' },
      { english: 'Can we reschedule the meeting?', chinese: '我们能重新安排会议时间吗？', phonetic: '/kæn wiː ˌriːˈʃedʒuːl ðə ˈmiːtɪŋ/' },
      { english: 'Please copy me on that email.', chinese: '那封邮件请抄送我。', phonetic: '/pliːz ˈkɑːpi miː ɑːn ðæt ˈiːmeɪl/' },
      { english: 'I have a question about the project.', chinese: '我有一个关于项目的问题。', phonetic: '/aɪ hæv ə ˈkwestʃən əˈbaʊt ðə ˈprɑːdʒekt/' },
      { english: 'Let us discuss this offline.', chinese: '我们线下再讨论这个。', phonetic: '/let ʌs dɪˈskʌs ðɪs ˈɔːflaɪn/' },
      { english: 'I will follow up on this issue.', chinese: '我会跟进这个问题。', phonetic: '/aɪ wɪl ˈfɑːloʊ ʌp ɑːn ðɪs ˈɪʃuː/' },
      { english: 'The deadline is this Friday.', chinese: '截止日期是本周五。', phonetic: '/ðə ˈdedlaɪn ɪz ðɪs ˈfraɪdeɪ/' },
      { english: 'We need to prioritize this task.', chinese: '我们需要优先处理这个任务。', phonetic: '/wiː niːd tuː praɪˈɔːrətaɪz ðɪs tæsk/' },
      { english: 'Thank you for your hard work.', chinese: '感谢你的辛苦付出。', phonetic: '/θæŋk juː fɔːr jʊr hɑːrd wɜːrk/' },
      { english: 'Let us take a ten-minute break.', chinese: '我们休息十分钟吧。', phonetic: '/let ʌs teɪk ə ten ˈmɪnɪt breɪk/' },
      { english: 'Could you repeat what you just said?', chinese: '你能重复一下刚才说的吗？', phonetic: '/kʊd juː rɪˈpiːt wʌt juː dʒʌst sed/' },
      { english: 'I completely agree with that proposal.', chinese: '我完全同意那个提案。', phonetic: '/aɪ kəmˈpliːtli əˈɡriː wɪð ðæt prəˈpoʊzl/' },
      { english: 'I have a different opinion on this.', chinese: '在这点上我有不同意见。', phonetic: '/aɪ hæv ə ˈdɪfrənt əˈpɪnjən ɑːn ðɪs/' },
      { english: 'Let me summarize what we decided.', chinese: '让我总结一下我们的决定。', phonetic: '/let miː ˈsʌməraɪz wʌt wiː dɪˈsaɪdɪd/' },
      { english: 'The meeting is adjourned.', chinese: '会议结束。', phonetic: '/ðə ˈmiːtɪŋ ɪz əˈdʒɜːrnd/' },
    ],
  },
  {
    course_name: '旅游英语实用',
    description: '出国旅游常用的英语对话和表达（中等难度）',
    difficulty: 'medium',
    category: '旅游',
    sentences: [
      { english: 'I would like to check in, please.', chinese: '我想办理入住，谢谢。', phonetic: '/aɪ wʊd laɪk tuː tʃek ɪn, pliːz/' },
      { english: 'I have a reservation for two nights.', chinese: '我预订了两晚。', phonetic: '/aɪ hæv ə ˌrezərˈveɪʃn fɔːr tuː naɪts/' },
      { english: 'Can I see your passport, please?', chinese: '请出示您的护照。', phonetic: '/kæn aɪ siː jʊr ˈpæspɔːrt, pliːz/' },
      { english: 'What time is checkout?', chinese: '退房时间是几点？', phonetic: '/wʌt taɪm ɪz ˈtʃekaʊt/' },
      { english: 'Is breakfast included?', chinese: '包含早餐吗？', phonetic: '/ɪz ˈbrekfəst ɪnˈkluːdɪd/' },
      { english: 'Can I have a room with a sea view?', chinese: '我能要一间海景房吗？', phonetic: '/kæn aɪ hæv ə ruːm wɪð ə siː vjuː/' },
      { english: 'The air conditioner is not working.', chinese: '空调坏了。', phonetic: '/ði er kənˈdɪʃənər ɪz nɑːt ˈwɜːrkɪŋ/' },
      { english: 'Could you send someone to fix it?', chinese: '能叫人来修一下吗？', phonetic: '/kʊd juː send ˈsʌmwʌn tuː fɪks ɪt/' },
      { english: 'I would like to check out now.', chinese: '我想现在退房。', phonetic: '/aɪ wʊd laɪk tuː tʃek aʊt naʊ/' },
      { english: 'Where is the tourist information center?', chinese: '旅游咨询中心在哪里？', phonetic: '/wer ɪz ðə ˈtʊrɪst ˌɪnfərˈmeɪʃn ˈsentər/' },
      { english: 'How much is the entrance fee?', chinese: '门票多少钱？', phonetic: '/haʊ mʌtʃ ɪz ði ˈentrəns fiː/' },
      { english: 'Is there a guided tour available?', chinese: '有导游带领的游览吗？', phonetic: '/ɪz ðer ə ˈɡaɪdɪd tʊr əˈveɪləbl/' },
      { english: 'Can you take a photo for us?', chinese: '你能帮我们拍张照吗？', phonetic: '/kæn juː teɪk ə ˈfoʊtoʊ fɔːr ʌs/' },
      { english: 'This place is absolutely beautiful.', chinese: '这个地方太美了。', phonetic: '/ðɪs pleɪs ɪz ˌæbsəˈluːtli ˈbjuːtɪfl/' },
      { english: 'I need to exchange some money.', chinese: '我需要兑换一些钱。', phonetic: '/aɪ niːd tuː ɪksˈtʃeɪndʒ sʌm ˈmʌni/' },
      { english: 'Where is the nearest ATM?', chinese: '最近的ATM在哪里？', phonetic: '/wer ɪz ðə ˈnɪrɪst eɪ tiː em/' },
      { english: 'I lost my wallet.', chinese: '我的钱包丢了。', phonetic: '/aɪ lɔːst maɪ ˈwɑːlɪt/' },
      { english: 'Where is the police station?', chinese: '警察局在哪里？', phonetic: '/wer ɪz ðə pəˈliːs ˈsteɪʃn/' },
      { english: 'Could you recommend some local food?', chinese: '你能推荐一些当地美食吗？', phonetic: '/kʊd juː ˌrekəˈmend sʌm ˈloʊkl fuːd/' },
      { english: 'I really enjoyed my trip here.', chinese: '我在这里玩得很开心。', phonetic: '/aɪ ˈriːəli ɪnˈdʒɔɪd maɪ trɪp hɪr/' },
    ],
  },
  {
    course_name: '商务英语进阶',
    description: '商务场合常用的正式英语表达（较高难度）',
    difficulty: 'hard',
    category: '商务',
    sentences: [
      { english: 'I would like to schedule a conference call with your team.', chinese: '我想和贵团队安排一次电话会议。', phonetic: '/aɪ wʊd laɪk tuː ˈskedʒuːl ə ˈkɑːnfərəns kɔːl wɪð jʊr tiːm/' },
      { english: 'Please find the attached quarterly report for your review.', chinese: '请查收附件中的季度报告供您审阅。', phonetic: '/pliːz faɪnd ði əˈtætʃt ˈkwɔːrtərli rɪˈpɔːrt fɔːr jʊr rɪˈvjuː/' },
      { english: 'We would like to propose a strategic partnership with your company.', chinese: '我们希望与贵公司建立战略合作伙伴关系。', phonetic: '/wiː wʊd laɪk tuː prəˈpoʊz ə strəˈtiːdʒɪk ˈpɑːrtnərʃɪp wɪð jʊr ˈkʌmpəni/' },
      { english: 'Could you provide us with a detailed quotation?', chinese: '能否为我们提供一份详细的报价单？', phonetic: '/kʊd juː prəˈvaɪd ʌs wɪð ə ˈdiːteɪld kwoʊˈteɪʃn/' },
      { english: 'We need to negotiate the terms of the contract.', chinese: '我们需要就合同条款进行谈判。', phonetic: '/wiː niːd tuː nɪˈɡoʊʃieɪt ðə tɜːrmz ʌv ðə ˈkɑːntrækt/' },
      { english: 'Our company specializes in software development.', chinese: '我们公司专注于软件开发。', phonetic: '/ˈaʊər ˈkʌmpəni ˈspeʃəlaɪzɪz ɪn ˈsɔːftwer dɪˈveləpmənt/' },
      { english: 'I would like to introduce our latest product line.', chinese: '我想介绍一下我们最新的产品线。', phonetic: '/aɪ wʊd laɪk tuː ˌɪntrəˈduːs ˈaʊər ˈleɪtəst ˈprɑːdʌkt laɪn/' },
      { english: 'What is the minimum order quantity?', chinese: '最小起订量是多少？', phonetic: '/wʌt ɪz ðə ˈmɪnɪməm ˈɔːrdər ˈkwɑːntəti/' },
      { english: 'We can offer you a five percent discount for bulk orders.', chinese: '对于大额订单我们可以给您百分之五的折扣。', phonetic: '/wiː kæn ˈɔːfər juː ə faɪv pərˈsent ˈdɪskaʊnt fɔːr bʌlk ˈɔːrdərz/' },
      { english: 'Payment is due within thirty days of invoice.', chinese: '付款需在发票开具后三十天内完成。', phonetic: '/ˈpeɪmənt ɪz duː wɪˈðɪn ˈθɜːrti deɪz ʌv ˈɪnvɔɪs/' },
      { english: 'We guarantee delivery within two weeks.', chinese: '我们保证两周内交货。', phonetic: '/wiː ˌɡærənˈtiː dɪˈlɪvəri wɪˈðɪn tuː wiːks/' },
      { english: 'I am writing to follow up on our previous conversation.', chinese: '我写这封邮件是为了跟进我们之前的谈话。', phonetic: '/aɪ æm ˈraɪtɪŋ tuː ˈfɑːloʊ ʌp ɑːn ˈaʊər ˈpriːviəs ˌkɑːnvərˈseɪʃn/' },
      { english: 'Let me clarify that point for you.', chinese: '让我为您澄清这一点。', phonetic: '/let miː ˈklærəfaɪ ðæt pɔɪnt fɔːr juː/' },
      { english: 'We value our long-term business relationship.', chinese: '我们非常重视双方的长期业务关系。', phonetic: '/wiː ˈvæljuː ˈaʊər lɔːŋ tɜːrm ˈbɪznəs rɪˈleɪʃnʃɪp/' },
      { english: 'I regret to inform you that we cannot meet your requirements.', chinese: '很遗憾地通知您我们无法满足您的要求。', phonetic: '/aɪ rɪˈɡret tuː ɪnˈfɔːrm juː ðæt wiː ˈkænnɑːt miːt jʊr rɪˈkwaɪərmənts/' },
      { english: 'We look forward to your prompt response.', chinese: '期待您的及时回复。', phonetic: '/wiː lʊk ˈfɔːrwərd tuː jʊr prɑːmpt rɪˈspɑːns/' },
      { english: 'Could we schedule a meeting to discuss this further?', chinese: '我们能否安排一次会议进一步讨论此事？', phonetic: '/kʊd wiː ˈskedʒuːl ə ˈmiːtɪŋ tuː dɪˈskʌs ðɪs ˈfɜːrðər/' },
      { english: 'Our revenue has grown by twenty percent year over year.', chinese: '我们的收入同比增长了百分之二十。', phonetic: '/ˈaʊər ˈrevənuː hæz ɡroʊn baɪ ˈtwenti pərˈsent jɪr ˈoʊvər jɪr/' },
      { english: 'We need to conduct due diligence before signing.', chinese: '在签署前我们需要进行尽职调查。', phonetic: '/wiː niːd tuː kənˈdʌkt duː ˈdɪlɪdʒəns bɪˈfɔːr ˈsaɪnɪŋ/' },
      { english: 'It was a pleasure doing business with you.', chinese: '与您合作非常愉快。', phonetic: '/ɪt wʌz ə ˈpleʒər ˈduːɪŋ ˈbɪznəs wɪð juː/' },
    ],
  },
  {
    course_name: '求职面试英语',
    description: '英语面试场景中的专业表达（较高难度）',
    difficulty: 'hard',
    category: '面试',
    sentences: [
      { english: 'Thank you for giving me this opportunity to interview.', chinese: '感谢您给我这次面试机会。', phonetic: '/θæŋk juː fɔːr ˈɡɪvɪŋ miː ðɪs ˌɑːpərˈtuːnəti tuː ˈɪntərvjuː/' },
      { english: 'Please tell me a little about yourself.', chinese: '请简单介绍一下你自己。', phonetic: '/pliːz tel miː ə ˈlɪtl əˈbaʊt jɔːrˈself/' },
      { english: 'I have five years of experience in software development.', chinese: '我有五年的软件开发经验。', phonetic: '/aɪ hæv faɪv jɪrz ʌv ɪkˈspɪriəns ɪn ˈsɔːftwer dɪˈveləpmənt/' },
      { english: 'I graduated from Peking University with a degree in computer science.', chinese: '我毕业于北京大学计算机科学专业。', phonetic: '/aɪ ˈɡrædʒueɪtɪd frʌm ˈpiːkɪŋ ˌjuːnɪˈvɜːrsəti wɪð ə dɪˈɡriː ɪn kəmˈpjuːtər ˈsaɪəns/' },
      { english: 'My greatest strength is my problem-solving ability.', chinese: '我最大的优势是解决问题的能力。', phonetic: '/maɪ ˈɡreɪtəstreŋθ ɪz maɪ ˈprɑːbləm ˈsɑːlvɪŋ əˈbɪləti/' },
      { english: 'I would say my weakness is that I am sometimes too detail-oriented.', chinese: '我想我的缺点是有时过于注重细节。', phonetic: '/aɪ wʊd seɪ maɪ ˈwiːknəs ɪz ðæt aɪ æm ˈsʌmtaɪmz tuː ˈdiːteɪl ˈɔːrientɪd/' },
      { english: 'Why do you want to join our company?', chinese: '你为什么想加入我们公司？', phonetic: '/waɪ duː juː wɑːnt tuː dʒɔɪn ˈaʊər ˈkʌmpəni/' },
      { english: 'I have long admired your company for its innovative culture.', chinese: '我一直很欣赏贵公司的创新文化。', phonetic: '/aɪ hæv lɔːŋ ədˈmaɪərd jʊr ˈkʌmpəni fɔːr ɪts ˈɪnəveɪtɪv ˈkʌltʃər/' },
      { english: 'Where do you see yourself in five years?', chinese: '你五年后的职业规划是什么？', phonetic: '/wer duː juː siː jɔːrˈself ɪn faɪv jɪrz/' },
      { english: 'I hope to grow into a senior technical leadership role.', chinese: '我希望成长为一名高级技术管理者。', phonetic: '/aɪ hoʊp tuː ɡroʊ ˈɪntuː ə ˈsiːniər ˈteknɪkl ˈliːdərʃɪp roʊl/' },
      { english: 'Can you describe a challenging project you worked on?', chinese: '你能描述一个你参与过的有挑战性的项目吗？', phonetic: '/kæn juː dɪˈskraɪb ə ˈtʃælɪndʒɪŋ ˈprɑːdʒekt juː wɜːrkt ɑːn/' },
      { english: 'I led a team of three developers to deliver the project on time.', chinese: '我带领一个三人开发团队按时交付了项目。', phonetic: '/aɪ led ə tiːm ʌv θriː dɪˈveləpərz tuː dɪˈlɪvər ðə ˈprɑːdʒekt ɑːn taɪm/' },
      { english: 'How do you handle pressure and tight deadlines?', chinese: '你如何应对压力和紧迫的截止日期？', phonetic: '/haʊ duː juː ˈhændl ˈpreʃər ænd taɪt ˈdedlaɪnz/' },
      { english: 'I prioritize tasks and communicate with stakeholders proactively.', chinese: '我会划分任务优先级并主动与利益相关方沟通。', phonetic: '/aɪ praɪˈɔːrətaɪz tæsks ænd kəˈmjuːnɪkeɪt wɪð ˈsteɪkhoʊldərz proʊˈæktɪvli/' },
      { english: 'What is your expected salary range?', chinese: '你的期望薪资范围是多少？', phonetic: '/wʌt ɪz jʊr ɪkˈspektɪd ˈsæləri reɪndʒ/' },
      { english: 'I am looking for a salary in the range of twenty to twenty-five thousand per month.', chinese: '我期望的月薪范围是两万到两万五千元。', phonetic: '/aɪ æm ˈlʊkɪŋ fɔːr ə ˈsæləri ɪn ðə reɪndʒ ʌv ˈtwenti tuː ˌtwentiˈfaɪv ˈθaʊzənd pɜːr mʌnθ/' },
      { english: 'Do you have any questions for us?', chinese: '你有什么问题想问我们吗？', phonetic: '/duː juː hæv ˈeni ˈkwestʃənz fɔːr ʌs/' },
      { english: 'What does the onboarding process look like for this role?', chinese: '这个岗位的入职流程是怎样的？', phonetic: '/wʌt dʌz ði ˈɑːnbɔːrdɪŋ ˈprɑːses lʊk laɪk fɔːr ðɪs roʊl/' },
      { english: 'When can I expect to hear back from you?', chinese: '我什么时候能收到您的回复？', phonetic: '/wen kæn aɪ ɪkˈspekt tuː hɪr bæk frʌm juː/' },
      { english: 'I am very excited about the possibility of joining your team.', chinese: '我对加入贵团队的可能性感到非常期待。', phonetic: '/aɪ æm ˈveri ɪkˈsaɪtɪd əˈbaʊt ðə ˌpɑːsəˈbɪləti ʌv ˈdʒɔɪnɪŋ jʊr tiːm/' },
    ],
  },
];

module.exports = builtinCourses;
